### ISSUE TITLE
Support for Rubocop 0.28.0 

### ISSUE THREAD

**Issue by michaelachrisco** [e2/hound-tools#1]
Rubocop has some new features I would like to use. Hound tools currently supports Rubocop up to 0.25.0.

https://github.com/bbatsov/rubocop/releases/tag/v0.28.0

**Comment by e2** [comment]
Unfortunately, the Rubocop version has to match the one in Hound - or you will get different errors in Hound and when running Rubocop manually. ;(

See here: https://github.com/thoughtbot/hound/blob/master/Gemfile#L29

**Comment by michaelachrisco** [comment]
Ah I see now. Darn...

Thanks for the update. I see: https://github.com/thoughtbot/hound/issues/472 now in hound.

**Comment by e2** [comment]
I just added this: https://github.com/thoughtbot/hound/issues/552

**Comment by michaelachrisco** [comment]
Excellent. :+1:  We could definitely use this feature around the office.
